import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('link', { name: 'Login' }).first().click();
  await page.getByRole('link', { name: 'Sign up here' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('ben3@kainos.com');
  await page.getByRole('textbox', { name: 'Password', exact: true }).click();
  await page.getByRole('textbox', { name: 'Password', exact: true }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password', exact: true }).fill('Password123123!');
  await page.getByRole('button', { name: 'Show password' }).click();
  await page.getByRole('textbox', { name: 'Password', exact: true }).click();
  await page.getByRole('textbox', { name: 'Password', exact: true }).click();
  await page.getByRole('textbox', { name: 'Password', exact: true }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Password', exact: true }).fill('Password123!');
  await page.getByRole('textbox', { name: 'Confirm Password' }).click();
  await page.getByRole('textbox', { name: 'Confirm Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Confirm Password' }).fill('Password123!');
  await page.getByRole('textbox', { name: 'Password', exact: true }).click();
  await page.getByRole('textbox', { name: 'Password', exact: true }).click();
  await page.getByRole('textbox', { name: 'Password', exact: true }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Password', exact: true }).press('ControlOrMeta+c');
  await page.getByRole('textbox', { name: 'Confirm Password' }).click();
  await page.getByRole('textbox', { name: 'Confirm Password' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Confirm Password' }).fill('Password123!');
  await page.getByRole('textbox', { name: 'Confirm Password' }).click();
  await page.getByRole('checkbox', { name: 'I agree to the' }).check();
  await page.getByRole('button', { name: 'Create Account' }).click();
});